name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Create env file
      run: |
        mkdir -p config
        echo "${{ secrets.ENV_CONTENT }}" > config/config.env

      run: |
        echo "${{ secrets.YML_CONTENT }}" > config/config.yml

    - name: Deploy with Docker Compose
      run: docker-compose --env-file config/config.env up --build -d
